config/routes.rb
Rails.application.routes.draw do

  root 'jobs#search'

  get 'jobs/search'
  get 'jobs/clear'

end

app/models/job.rb
class Job
  include ActiveModel::Model
  include ActiveModel::Validations

  attr_accessor :company
  attr_accessor :categories
  attr_accessor :levels
  attr_accessor :locations

  def is_empty
    company.blank? && categories.blank? && levels.blank? && locations.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
require 'net/http'
require 'json'

class JobsController < ApplicationController

  MUSE_API_URL = 'https://api-v2.themuse.com/jobs'
  API_KEY = 'd46f707a798be0f5d9176416475e9a4700f0d515f26df799119bbee08b3041d6'

  def search
    @jobs_filter = Job.new
    if !params['job'].nil?
      @jobs_filter.company = params['job']['company']
      @jobs_filter.categories = []
      params['job']['categories'].each do |category|
        @jobs_filter.categories << category unless category.blank?
      end
      @jobs_filter.levels = []
      params['job']['levels'].each do |level|
        @jobs_filter.levels << level unless level.blank?
      end
      @jobs_filter.locations = params['job']['locations']
      # params['job']['locations'].each do |location|
      #   @jobs_filter.locations << location unless location.blank?
      # end
    end

    @levels = [
      'Internship',
      'Entry Level',
      'Mid Level',
      'Senior Level'
    ]

    @categories = [
      'Account Management',
      'Business & Strategy',
      'Creative & Design',
      'Customer Service',
      'Data Science',
      'Editorial',
      'Education',
      'Engineering',
      'Finance',
      'Fundraising & Development',
      'Healthcare & Medicine',
      'HR & Recruiting',
      'Legal',
      'Marketing & PR',
      'Operations',
      'Project & Product Management',
      'Retail Sales',
      'Social Media & Community'
    ]

    # puts "#{MUSE_API_URL}?api_key=#{API_KEY}&page=0"

    if @jobs_filter.is_empty
      uri = URI.parse("#{MUSE_API_URL}?api_key=#{API_KEY}&page=0")
    else
      unparsed_uri = "#{MUSE_API_URL}?api_key=#{API_KEY}&page=0"
      unparsed_uri << "&company=#{@jobs_filter.company}" unless @jobs_filter.company.nil?
      @jobs_filter.categories.each do |category|
        unparsed_uri << "&category=#{category}" unless category.blank?
      end
      @jobs_filter.levels.each do |level|
        unparsed_uri << "&level=#{level}" unless level.blank?
      end
      uri = URI.parse(unparsed_uri)
      @has_filter = true
    end
    response = Net::HTTP.get(uri)
    @jobs_data = JSON.parse(response)

    @total = @jobs_data['total']
    @results = @jobs_data['results']
  end

  def clear
    redirect_to jobs_search_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  # Bad name, but get's comma separated list of names for category, location
  # and level
  def get_comma_separated_list_of_names(the_list)
    the_string = ''
    return the_string if the_list.nil?
    the_list.each do |item|
      the_string << item['name'] + ','
    end
    the_string[0..-2]
  end
end

app/views/jobs/search.html.erb
<!-- Monster HTML file containing the whole app. That's right everything. -->
<html>
  <body>
    <% unless @has_filter %>
      <div>
        <%= button_tag "Edit Job Filters", class: "btn btn-large btn-success" %>
      </div>
    <% end %>

    <div id="search-form">
      <%= form_for @jobs_filter, :url => jobs_search_path, :method => :get do |f| %>
        <div class="col-md-12">
          <div class="col-md-4">
            <%= f.label :company %>:
            <%= f.text_field :company, class: "form-control" %><br />

            <%= f.label :categories %>:
            <%= f.select :categories, options_for_select(@categories, @jobs_filter.categories), {}, {multiple: true, class: "form-control"} %><br />
          </div>
          <div class="col-md-4">
            <%= f.label :levels %>:
            <%= f.select :levels, options_for_select(@levels, @jobs_filter.levels), {}, {multiple: true, class: "form-control"} %><br />

            <%= f.label :locations %>:
            <%= f.text_field :locations, class: "form-control" %><br />
          </div>
        </div>
        <div class="col-md-4">
          <%= f.submit "Search", class: "btn btn-large btn-primary" %>
          <%= button_to "Clear", jobs_clear_path, class: "btn btn-large btn-secondary" %>
        </div>
      <% end %>
    </div>

    <hr>

    <!-- Results section, should be a partial but hacking -->

    <div id="job-results" class="col-md-12" >
      <% unless @results.nil? %>
        <table class="table">
        <thead>
          <tr>
            <th>Company</th>
            <th>Short Name</th>
            <th>Category</th>
            <th>Level</th>
            <th>Location</th>
          </tr>
        </thead>
        <tbody>
          <% @results.each do |job| %>
            <tr>
              <td><%= job['company']['name'] %></td>
              <td><%= job['name'] %></td>
              <td><%= get_comma_separated_list_of_names job['categories'] %></td>
              <td><%= get_comma_separated_list_of_names job['levels'] %></td>
              <td><%= get_comma_separated_list_of_names job['locations'] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Afflatus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>